name = "benefactor-api"
main = "src/index.ts"
compatibility_date = "2024-11-18"
compatibility_flags = [ "nodejs_compat" ]

[observability]
enabled = true

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "4583f772f1fc4061826b649b50b76b20"
