name = "benefactor-api"
main = "src/index.ts"
compatibility_date = "2024-11-18"
compatibility_flags = [ "nodejs_compat" ]

[observability]
enabled = true

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "9c0e2ab42d1a4be08dba446a5173a341"
