name = "benefactor-api"
main = "src/index.ts"
compatibility_date = "2024-11-18"
compatibility_flags = [ "nodejs_compat" ]

[observability]
enabled = true

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "b837aeed6eef4b7fbe9eab712ef5eea9"
