"use client";

import React, { createContext, useContext, useEffect, useState } from "react";

export type LangCode = "en" | "lt" | "ru" | "tr" | "de" | "fr" | "es";

const SUPPORTED: LangCode[] = ["en", "lt", "ru", "tr", "de", "fr", "es"];

type Dict = Record<string, string>;

// =============================================================================
// English — source of truth. All UI strings live here.
// =============================================================================
const en: Dict = {
  // ─── Navbar / common chrome ─────────────────────────────────────────────
  search: "Search",
  donate: "Donate",
  fundraise: "Fundraise",
  about: "About",
  signin: "Sign in",
  startBenefactor: "Start a Benefactor",
  openMenu: "Open menu",
  closeMenu: "Close menu",
  profile: "Profile",
  backToCampaign: "Back to campaign",
  back: "Back",
  securedByStripe: "Secured by Stripe",

  // Navbar dropdowns
  donateBrowse: "Browse fundraisers",
  donateCategories: "Browse by category",
  donateFeatured: "Featured campaigns",
  fundraiseStart: "Start a campaign",
  fundraiseHow: "How it works",
  fundraiseTips: "Fundraising tips",
  aboutHow: "How Benefactor works",
  aboutAbout: "About Benefactor",
  aboutCareers: "Careers",

  // Mobile drawer
  navHome: "Home",
  navDashboard: "Dashboard",
  navFundraisers: "Fundraisers",
  navDonations: "Donations",
  navAccount: "Account",
  navProfile: "Profile",

  // Search modal / page
  searchPlaceholder: "Search campaigns, causes, or organizers",
  searchEmpty: "Start typing to find campaigns",
  searchResults: "Results",
  searchNoResults: "No campaigns match your search",

  // ─── Hero (home) ────────────────────────────────────────────────────────
  heroTitle1: "World wide",
  heroTitle2: "fundraising",
  heroTitle3: "platform",
  heroSubtitle: "Every story matters. Every donation counts. Start your campaign in minutes and reach a global community of givers.",
  heroFeeFree: "No fee to start fundraising",
  heroReviewed: "Every campaign reviewed before launch",
  heroWithdraw: "Withdraw to your bank anytime",
  heroFeaturedStoryBadge: "Featured story",
  heroUnmuteVideo: "Unmute video",
  heroMuteVideo: "Mute video",
  heroWatchOnYoutube: "Watch on YouTube",
  heroHelpFamilyLithuania: "Help a Family in Lithuania",
  heroDonateNow: "Donate now",

  // ─── Checkout success ──────────────────────────────────────────────────
  successHeading: "Thank you for your donation!",
  successTagline: "Every donation is a new hope.",
  successBody: "Your kindness brings real change to someone's life today. We've sent a receipt to your email, so keep an eye on your inbox for updates on the impact of your gift.",
  successBackHome: "Back home",
  successViewCampaign: "View campaign",
  successShare: "Share",
  successShareText: "I just supported a cause on Benefactor. Every donation is a new hope. Join me:",
  successReceiptNote: "A receipt has been sent to your email. Powered by Stripe, secure payments.",

  // ─── Featured (home) ────────────────────────────────────────────────────
  featuredHeading: "Featured campaign",
  featuredViewAll: "View all",
  featuredRaisedOf: "raised of {total}",
  featuredPctFunded: "{pct}% funded",
  featuredStatRaised: "Raised",
  featuredStatDonors: "Donors",
  featuredStatGoal: "Goal",
  featuredShareAria: "Share campaign",

  // ─── Categories (home) ──────────────────────────────────────────────────
  categoriesHeading: "Categories",
  catMedical: "Medical",
  catEmergency: "Emergency",
  catEducation: "Education",
  catAnimals: "Animals",
  catBusiness: "Business",
  catCommunity: "Community",
  catEnvironment: "Environment",
  catCreative: "Creative",
  catSport: "Sport",
  catFamily: "Family",
  catMemorial: "Memorial",
  catTravel: "Travel",

  // ─── How & Trust (home) ─────────────────────────────────────────────────
  howHeading: "How it works",
  howStep1Title: "Create your campaign",
  howStep1Desc: "Add your story, a photo, and a fundraising goal. Takes a few minutes.",
  howStep2Title: "Share with your network",
  howStep2Desc: "Send your campaign link to friends, family, and a global audience.",
  howStep3Title: "Receive donations",
  howStep3Desc: "Funds go to your verified bank account. No platform fee.",
  trustHeading: "How your donation is protected",
  trustItem1Title: "Payments secured by Stripe",
  trustItem1Desc: "All transactions are handled by Stripe with PCI DSS Level 1 compliance.",
  trustItem2Title: "Verified organizers",
  trustItem2Desc: "Every fundraiser is reviewed and the organizer identity confirmed before going live.",
  trustItem3Title: "Direct bank withdrawals",
  trustItem3Desc: "Funds are paid out to your verified bank account by SEPA or wire transfer.",
  poweredBy: "Powered by",

  // ─── Logo showcase (home) ───────────────────────────────────────────────
  showcaseBadge: "Future project",
  showcaseTitle: "Kids Camp Center",
  showcaseDesc: "Our next initiative is a Kids Camp Center in Lithuania, a safe space where children can learn, play, and grow together. We are preparing to launch the fundraising campaign very soon. Follow us to support the project and watch every stage of the journey unfold with us.",
  showcaseCta: "Support the project",
  showcaseImageCaption: "Coming soon, a place built for every child",
  showcaseImageAlt: "Kids Camp Center",
  // ─── Kids Camp support modal ───
  supportClose: "Close",
  supportComingSoonBadge: "Coming soon",
  supportHeading: "Be part of the Kids Camp Center journey",
  supportLeadCopy:
    "We are preparing to launch the fundraising campaign very soon. Until then, you can share your ideas, partner with us, donate, or join as a volunteer. Every message reaches our team directly.",
  supportRoleLabel: "I would like to help as",
  supportRole_donor: "A donor",
  supportRole_volunteer: "A volunteer",
  supportRole_partner: "A partner or sponsor",
  supportRole_other: "Something else",
  supportName: "Your name",
  supportEmail: "Email",
  supportMessage: "Your message",
  supportMessagePlaceholder:
    "Share your suggestion, organisation idea, or how you would like to contribute…",
  supportPrivacyNote:
    "Your details are sent privately to the Benefactor team. We will never share them.",
  supportSubmit: "Send to the team",
  supportThanksTitle: "Thank you for stepping up",
  supportThanksBody:
    "Your message is ready in your email client. We will reply as soon as we can and keep you posted as the project progresses.",

  // ─── Useful links (home) ────────────────────────────────────────────────
  usefulBadge: "Useful links",
  usefulHeading: "Want to know more about fundraising?",
  usefulLink1Title: "What is fundraising?",
  usefulLink1Desc: "Everything you need to know about fundraising.",
  usefulLink2Title: "How to fundraise",
  usefulLink2Desc: "How to get started with your own fundraising page.",
  usefulLink3Title: "Fundraising tips",
  usefulLink3Desc: "How to maximise donations and raise more.",
  usefulLink4Title: "Create the perfect fundraising page",
  usefulLink4Desc: "Five simple steps for a successful fundraising page.",

  // ─── Footer ─────────────────────────────────────────────────────────────
  footerCategories: "Categories",
  footerAbout: "About",
  footerStartLabel: "Start a Benefactor",
  footerFundraisingCategories: "Fundraising categories",
  footerHowItWorks: "How Benefactor works",
  footerAboutLink: "About Benefactor",
  footerCareers: "Careers",
  footerCopyright: "© {year} Benefactor Platform. All rights reserved.",
  footerTrustSecure: "Secure payments",
  footerTrustVerified: "Verified fundraising flow",
  footerTrustData: "Data protection",
  footerLegalTerms: "Terms",
  footerLegalPrivacy: "Privacy",
  footerLegalContact: "Contact",
  footerStripeNotice: "All donations are processed by Stripe over encrypted channels. We never store full card details. Every fundraiser is reviewed before going live and the organizer identity is verified.",

  // Locale selector
  localeRegionLanguage: "Region & language",
  localeSave: "Save settings",
  localeClose: "Close",
  localeLanguage: "Language",
  localeCountry: "Country",
  localeUpdateSettings: "Update your settings",
  localeUpdateDesc: "Set what language you speak and where you live.",
  localeSelectLanguage: "Select a language",
  localeSelectCountry: "Select a country",
  cancel: "Cancel",
  save: "Save",

  // ─── Campaign / donation common ─────────────────────────────────────────
  raised: "Raised",
  donations: "Donations",
  goal: "Goal",
  donatePlain: "Donate",
  share: "Share",
  organizer: "Organizer",
  contact: "Contact",
  raisedOfGoal: "raised of {total} goal",
  donorsLabel: "donors",
  recentDonors: "Recent Donors",
  totalCount: "{count} total",
  sortRecent: "Recent",
  sortTop: "Top",
  anonymous: "Anonymous",
  showLess: "Show less",
  seeAllDonors: "See all {count} donors",
  funded: "funded",
  verified: "Verified",
  readMore: "Read more",
  readLess: "Read less",
  aboutThisCampaign: "About this campaign",
  relatedFundraisers: "Related Fundraisers",
  prevImage: "Previous image",
  nextImage: "Next image",
  openFullscreen: "Open fullscreen",
  viewImage: "View",
  galleryImage: "Gallery image {n}",
  showImage: "Show image {n}",

  // ─── Share modal ────────────────────────────────────────────────────────
  shareTitle: "Share this campaign",
  shareSubtitle: "Help spread the word — every share helps the cause reach more people.",
  shareCopy: "Copy link",
  shareCopied: "Link copied",
  shareWhatsapp: "WhatsApp",
  shareTwitter: "X / Twitter",
  shareFacebook: "Facebook",
  shareTelegram: "Telegram",
  shareEmail: "Email",
  shareNative: "More options",
  shareClose: "Close",

  // ─── Checkout ───────────────────────────────────────────────────────────
  checkoutYouAreDonatingTo: "You are donating to",
  checkoutCampaignTitle: "Help a family in Lithuania stay warm this winter",
  checkoutPctFunded: "{pct}% funded",
  checkoutToGo: "{amount} to go",
  checkoutGiveOnce: "Give once",
  checkoutMonthly: "Monthly",
  checkoutMonthlyNote: "Monthly giving builds steady support for the cause.",
  checkoutChooseAmount: "Choose an amount",
  checkoutPopular: "Popular",
  checkoutOtherAmount: "Other amount",
  checkoutTipHeading: "Tip Benefactor",
  checkoutTipDesc: "We charge 0% to organizers. Tips are optional and help us keep the platform free.",
  checkoutTipPercentLabel: "Tip percentage",
  checkoutApply: "Apply",
  checkoutCancel: "Cancel",
  checkoutUseSlider: "Use slider",
  checkoutEnterCustomTip: "Enter custom tip",
  checkoutPaymentMethod: "Payment method",
  checkoutOrPayCard: "Or pay with card",
  checkoutCurrency: "Donation currency",
  checkoutCurrencyNote: "We collect in either currency. Stripe handles conversion to our payout account.",
  checkoutEmail: "Email for receipt",
  checkoutEmailPlaceholder: "you@email.com",
  checkoutEmailNote: "We'll send you a receipt and tax-deductible confirmation. We never share your email.",
  checkoutEmailRequired: "Email required",
  checkoutEmailRequiredDesc: "Please enter a valid email address so we can send your donation receipt.",
  checkoutPaypalSoonTitle: "PayPal coming soon",
  checkoutPaypalSoonDesc: "PayPal isn't active yet. Please choose Apple Pay, Google Pay, Revolut Pay, or Card.",
  checkoutComingSoon: "Coming soon",
  checkoutOneTap: "One tap",
  checkoutPaypal: "PayPal",
  checkoutApplePay: "Apple Pay",
  checkoutGooglePay: "Google Pay",
  checkoutRevolutPay: "Revolut Pay",
  checkoutCard: "Credit or debit card",
  checkoutAnonOption: "Do not display my name publicly on the fundraiser.",
  checkoutShowName: "Show my name publicly on the fundraiser.",
  checkoutUpdatesOption: "Send me occasional updates from Benefactor.",
  checkoutSummary: "Summary",
  checkoutYourDonation: "Your donation",
  checkoutBenefactorTip: "Benefactor tip",
  checkoutTotalToday: "Total today",
  checkoutDonateNow: "Donate now",
  checkoutAgreeTerms: "By continuing you agree to our",
  checkoutAnd: "and",
  checkoutTermsLink: "Terms",
  checkoutPrivacyLink: "Privacy Policy",
  checkoutProtectionTitle: "Your donation is protected",
  checkoutProtectionDesc: "Payments are processed by Stripe over encrypted channels. In the rare case of fraud, we guarantee a full refund for up to a year.",
  checkoutLearnMore: "Learn more",
  checkoutPaymentFailed: "Payment failed",
  checkoutPageFooterTagline: "Worldwide fundraising platform",

  // ─── Marketing: How page ────────────────────────────────────────────────
  howPageEyebrow: "How it works",
  howPageTitlePart1: "From story to",
  howPageTitleEmph: "support",
  howPageTitlePart2: ", in minutes.",
  howPageLede: "Three steps. No platform fee. Every campaign reviewed before going live.",
  howStepAltTitle1: "Start your fundraiser",
  howStepAltDesc1: "Set a goal, write your story, and add photos. It takes a few minutes.",
  howStepAltTitle2: "Share with your network",
  howStepAltDesc2: "Send your fundraiser link to friends, family, and social channels.",
  howStepAltTitle3: "Receive donations",
  howStepAltDesc3: "Track progress, thank donors, and withdraw funds to your bank anytime.",
  howWhyHeading: "Why people choose Benefactor",
  howFeat1Title: "0% platform fee",
  howFeat1Desc: "Benefactor never takes a cut. More money goes to the people who need it.",
  howFeat2Title: "Donor protection",
  howFeat2Desc: "Every fundraiser is reviewed and the organizer identity is verified before launch.",
  howFeat3Title: "Fast withdrawals",
  howFeat3Desc: "Withdraw to your verified bank account by SEPA or wire transfer when you need to.",
  howFeat4Title: "Available across Europe",
  howFeat4Desc: "Raise and donate from anywhere in Europe. Compliance built in from day one.",
  howReadyHeading: "Ready to start?",
  howReadyDesc: "It takes a few minutes to launch a fundraiser and share it.",

  // ─── Marketing: About page ──────────────────────────────────────────────
  aboutEyebrow: "About",
  aboutTitlePart1: "Generosity, made",
  aboutTitleEmph: "simple",
  aboutTitlePart2: ".",
  aboutLede: "Benefactor is a fundraising platform built on transparency, trust, and zero platform fees.",
  aboutOurStory: "Our story",
  aboutStoryP1: "Benefactor started with a question we could not ignore: why is it still so hard for good people to raise money for good causes? We saw the friction firsthand. The distrust. The fees. The platforms that took too much and gave too little back.",
  aboutStoryP2: "So we built something different. Whether it is a family facing unexpected costs, a community rebuilding after a crisis, or a student chasing an opportunity, Benefactor exists to close the gap between compassion and action.",
  aboutWhatWeDo: "What we do",
  aboutWhatWeDoP: "We give people the simplest, most transparent way to raise and donate money online. No platform fees. Verified campaigns. Bank-grade security. And a team that reviews every fundraiser before it goes live.",
  aboutCommitment: "Our commitment",
  aboutStat1Label: "Platform fee",
  aboutStat2Label: "Review time",
  aboutStat3Label: "Encrypted payments",
  aboutStat4Label: "Standards compliant",
  aboutValues: "Our values",
  aboutValue1Title: "Radical transparency",
  aboutValue1Desc: "Every campaign reviewed. Every transaction traceable. Trust is earned, not claimed.",
  aboutValue2Title: "Simplicity first",
  aboutValue2Desc: "We obsess over removing friction. If it feels complicated, it is not finished.",
  aboutValue3Title: "Borderless compassion",
  aboutValue3Desc: "A good cause has no nationality. We build so generosity flows wherever it is needed.",

  // ─── Marketing: Careers page ────────────────────────────────────────────
  careersEyebrow: "Careers",
  careersTitlePart1: "Build the tools that help people",
  careersTitleEmph: "help each other",
  careersTitlePart2: ".",
  careersLede: "We are looking for passionate people to join our mission.",
  careersWhyHeading: "Why work at Benefactor",
  careersPerk1Title: "Meaningful impact",
  careersPerk1Desc: "Your work directly helps people raise funds for the causes that matter most to them.",
  careersPerk2Title: "Remote-first",
  careersPerk2Desc: "Work from anywhere with flexible hours and async-friendly collaboration.",
  careersPerk3Title: "Growth and learning",
  careersPerk3Desc: "Access mentorship, learning budgets, and opportunities to develop your career.",
  careersPerk4Title: "Competitive benefits",
  careersPerk4Desc: "Comprehensive health insurance, generous PTO, and equity for all team members.",
  careersPerk5Title: "Inclusive team",
  careersPerk5Desc: "We celebrate diversity and foster an environment where everyone can thrive.",
  careersPerk6Title: "Giving back",
  careersPerk6Desc: "Paid volunteer days and donation matching to causes you care about personally.",
  careersOpenPositions: "Open positions",
  careersVolunteerCallout:
    "We are also looking for volunteers. If you would like to give your time, skills or ideas to help our campaigns reach more people, you are very welcome to apply too.",
  careersApply: "Apply",
  careersDeptEngineering: "Engineering",
  careersDeptDesign: "Design",
  careersDeptCommunity: "Community",
  careersDeptAnalytics: "Analytics",
  careersDeptMarketing: "Marketing",
  careersFullTime: "Full-time",
  careersVolunteer: "Volunteer",
  careersRoleVolunteer: "Volunteer — help us shape the platform",
  careersLocRemote: "Remote",
  careersLocLondon: "London, UK",
  careersRoleSeniorFrontend: "Senior Frontend Engineer",
  careersRoleProductDesigner: "Product Designer",
  careersRoleCommunityManager: "Community Manager",
  careersRoleDataAnalyst: "Data Analyst",
  careersRoleMarketingSpecialist: "Marketing Specialist",
  careersRoleContentEditor: "Content Editor",
  careersNoRoleHeading: "Do not see your role?",
  careersNoRoleDesc: "We are always looking for talented and passionate people. Send your CV and tell us how you would like to contribute.",
  careersGetInTouch: "Get in touch",

  // ─── Start (wizard) ─────────────────────────────────────────────────────
  wizardStepOf: "Step {current} of {total}",
  wizardBack: "Back",
  wizardSkip: "Skip",
  wizardContinue: "Continue",
  wizardReview: "Review",
  wizardSubmit: "Submit",
  wizardStepTitle0: "Let's begin your fundraising journey.",
  wizardStepSubtitle0: "Pick a category and location. We will guide you through the rest.",
  wizardStepTitle1: "Who will benefit from the funds?",
  wizardStepSubtitle1: "Tell us who the funds are intended for.",
  wizardStepTitle2: "Set your fundraising goal.",
  wizardStepSubtitle2: "You can always change this later.",
  wizardStepTitle3: "Make your fundraiser stand out.",
  wizardStepSubtitle3: "A great photo or short video makes all the difference.",
  wizardStepTitle4: "Tell donors your story.",
  wizardStepSubtitle4: "A clear story helps you connect with donors.",
  wizardStepTitle5: "Submit for review.",
  wizardStepSubtitle5: "Add your contact details and submit for approval.",
  wizardStepTitle6: "Your fundraiser is under review.",
  wizardStepSubtitle6: "Our team will review and contact you within 24 hours.",
  wizardSidebarStep1: "Category",
  wizardSidebarStep2: "Beneficiary",
  wizardSidebarStep3: "Goal",
  wizardSidebarStep4: "Media",
  wizardSidebarStep5: "Story",
  wizardSidebarStep6: "Review",

  stepCategoryHeading: "Where will the funds go?",
  stepCategoryDesc: "Choose the location where you plan to withdraw your funds.",
  stepCategorySupportedCountries: "Supported countries",
  stepCategoryCountry: "Country",
  stepCategoryPostcode: "Postcode",
  stepCategoryPostcodePlaceholder: "e.g. SW1A 1AA",
  stepCategoryWhichDescribes: "What best describes your fundraiser?",

  stepBeneficiaryHeading: "Who are you fundraising for?",
  stepBenYourselfTitle: "Yourself",
  stepBenYourselfDesc: "Funds are delivered to your bank account for your own use.",
  stepBenSomeoneTitle: "Someone else",
  stepBenSomeoneDesc: "Invite a beneficiary to receive funds, or distribute them yourself.",
  stepBenCharityTitle: "A charity",
  stepBenCharityDesc: "Funds are delivered to your chosen nonprofit.",

  stepGoalAmount: "Goal amount",
  stepGoalHint: "Fundraisers like yours typically aim for £3,500 or more.",
  stepGoalRecommended: "Recommended",
  stepGoalAutoTitle: "Automated goal setting",
  stepGoalAutoDesc: "We adjust your goal gradually as donations come in.",
  stepGoalMore: "More",
  stepGoalAutoAria: "Toggle automated goal",

  stepMediaHeading: "Add a cover photo or video",
  stepMediaDesc: "A clear, real photo helps donors connect with your story. You can update it later.",
  stepMediaReplace: "Replace",
  stepMediaRemove: "Remove",
  stepMediaRemoveAria: "Remove cover",
  stepMediaDropHint: "Drag a photo here, or click to upload",
  stepMediaFileHint: "JPG, PNG, or MP4 up to 50MB",
  stepMediaCoverAlt: "Cover preview",

  stepStoryTitleLabel: "Fundraiser title",
  stepStoryTitlePlaceholder: "Help a family in...",
  stepStoryStoryLabel: "Your story",
  stepStoryStoryPlaceholder: "Share why you are raising funds, who it will help, and how the money will be used.",
  stepStoryTip: "Tip: a clear, honest story raises 2x more than a vague one.",

  stepReviewNotSet: "Not set",
  stepReviewEdit: "Edit",
  stepReviewTitle: "Title",
  stepReviewGoal: "Goal",
  stepReviewCategory: "Category",
  stepReviewLocation: "Location",
  stepReviewStory: "Story",
  stepReviewContact: "Contact details",
  stepReviewEmail: "Email",
  stepReviewPhone: "Phone",
  stepReviewEmailPlaceholder: "name@example.com",
  stepReviewPhonePlaceholder: "+44 7700 900000",
  stepReviewHint: "Our team uses these details to reach you for a brief review call before your fundraiser goes live.",
  stepReviewPreview: "Preview",
  stepReviewPreviewSoon: "Preview coming soon",
  stepReviewSubmit: "Submit for review",
  stepReviewCoverAlt: "Cover",

  stepShareSubmissionReceived: "Submission received.",
  stepShareDesc: "Your fundraiser has been sent to our team for review. We manually verify every campaign to keep the platform trusted.",
  stepShareWhatNext: "What happens next",
  stepShareStep1Title: "Team review",
  stepShareStep1Desc: "Our team reviews your fundraiser within 24 to 48 hours.",
  stepShareStep2Title: "Meeting request",
  stepShareStep2Desc: "We contact you by email or phone to schedule a brief introductory call.",
  stepShareStep3Title: "Launch",
  stepShareStep3Desc: "Once approved, your fundraiser goes live on the platform.",
  stepShareGoDashboard: "Go to dashboard",
  stepShareBackHome: "Back home",

  // ─── Auth (Sign in) ─────────────────────────────────────────────────────
  authWelcomeBack: "Welcome back",
  authCreateAccount: "Create your account",
  authSigninDesc: "Sign in to continue.",
  authSignupDesc: "Start your fundraiser in minutes.",
  authContinueGoogle: "Continue with Google",
  authOr: "or",
  authEmail: "Email",
  authEmailPlaceholder: "name@example.com",
  authFullName: "Full name",
  authNamePlaceholder: "Jane Doe",
  authPassword: "Password",
  authPasswordPlaceholder: "At least 8 characters",
  authShowPassword: "Show password",
  authHidePassword: "Hide password",
  authContinue: "Continue",
  authSignIn: "Sign in",
  authCreate: "Create account",
  authUseDifferentEmail: "Use a different email",
  authNewToBenefactor: "New to Benefactor?",
  authAlreadyHave: "Already have an account?",
  authCreateLink: "Create an account",
  authSignInLink: "Sign in",
  authAgreeTerms: "By continuing you agree to our",
  authAnd: "and",
  authTerms: "Terms",
  authPrivacy: "Privacy Policy",
  authBackToBenefactor: "Back to Benefactor",
  authFailed: "Authentication failed",

  // ─── Dashboard ──────────────────────────────────────────────────────────
  dashYourAccount: "Your account",
  dashTitle: "Dashboard",
  dashNewFundraiser: "New fundraiser",
  dashYourFundraisers: "Your fundraisers",
  dashRecentActivity: "Recent activity",
  dashQuickActions: "Quick actions",
  dashStatTotalRaised: "Total raised",
  dashStatDonations: "Donations",
  dashStatSupporters: "Supporters",
  dashStatShares: "Shares",
  dashStatChangeWeek: "+{value}% this week",
  dashStatChangeToday: "+{value} today",
  dashStatChangeNew: "+{value} new",
  dashStatChangeWeekCount: "+{value} this week",
  dashSampleFundraiserTitle: "Help fund my education journey",
  dashSampleFundraiserMeta: "Created 2 days ago · Education",
  dashRaisedLower: "raised",
  dashOfGoalLower: "of {amount} goal",
  dashDonationsLower: "donations",
  dashManage: "Manage",
  dashLoading: "Loading…",
  dashActDonated: "donated",
  dashActShared: "shared your fundraiser",
  dashActTime2m: "2 minutes ago",
  dashActTime15m: "15 minutes ago",
  dashActTime1h: "1 hour ago",
  dashActTime2h: "2 hours ago",
  dashActTime3h: "3 hours ago",
  dashActDonorEmma: "Emma W.",
  dashActDonorJames: "James M.",
  dashActDonorSarah: "Sarah K.",
  dashActDonorAli: "Ali R.",
  dashActDonorAnonymous: "Anonymous",
  qaShareTitle: "Share fundraiser",
  qaShareDesc: "Share via social, email, or copy link.",
  qaEditTitle: "Edit campaign",
  qaEditDesc: "Update your story, photos, or goal.",
  qaWithdrawTitle: "Withdraw funds",
  qaWithdrawDesc: "Transfer raised funds to your bank.",

  // ─── Profile ────────────────────────────────────────────────────────────
  profileBreadcrumbDashboard: "Dashboard",
  profileBreadcrumbProfile: "Profile",
  profileSettings: "Settings",
  profileTitle: "Profile",
  profilePersonalInfo: "Personal information",
  profileNotifications: "Notifications",
  profileFullName: "Full name",
  profileEmail: "Email",
  profilePhone: "Phone",
  profileLanguage: "Preferred language",
  profileBio: "Bio",
  profileBioPlaceholder: "Tell us a bit about yourself.",
  profileEmailUpdates: "Email updates",
  profileEmailUpdatesDesc: "Get campaign news and donation receipts by email.",
  profileSmsUpdates: "SMS notifications",
  profileSmsUpdatesDesc: "Get critical alerts as text messages.",
  profileKeepCurrent: "Keep your details current so our team can reach you for campaign reviews.",
  profileSaved: "Saved",
  profileSave: "Save changes",
  profileChangePhoto: "Change photo",
  profileMemberSince: "Member since April 2024 · London, UK",
  profileTagVerified: "Verified",
  profileTagFundraiser: "Fundraiser",
  profileStatDonations: "Donations",
  profileStatProjects: "Projects",

  // ─── Errors / not found / loading ───────────────────────────────────────
  errorSomethingWentWrong: "Something went wrong",
  errorDefault: "An unexpected error occurred. Please try again.",
  errorTryAgain: "Try again",
  notFoundTitle: "Page not found",
  notFoundDesc: "The page you are looking for does not exist or has been moved.",
  notFoundBackHome: "Back home",
  notFoundLearnHow: "Learn how it works",
  loading: "Loading…",
};

// =============================================================================
// Lithuanian — natural, native-quality translations.
// =============================================================================
const lt: Dict = {
  // Navbar
  search: "Ieškoti",
  donate: "Aukoti",
  fundraise: "Rinkti lėšas",
  about: "Apie",
  signin: "Prisijungti",
  startBenefactor: "Pradėti rinkliavą",
  openMenu: "Atidaryti meniu",
  closeMenu: "Uždaryti meniu",
  profile: "Profilis",
  backToCampaign: "Grįžti į rinkliavą",
  back: "Atgal",
  securedByStripe: "Saugumą užtikrina Stripe",

  donateBrowse: "Naršyti rinkliavas",
  donateCategories: "Pagal kategoriją",
  donateFeatured: "Rekomenduojamos rinkliavos",
  fundraiseStart: "Pradėti rinkliavą",
  fundraiseHow: "Kaip tai veikia",
  fundraiseTips: "Lėšų rinkimo patarimai",
  aboutHow: "Kaip veikia Benefactor",
  aboutAbout: "Apie Benefactor",
  aboutCareers: "Karjera",

  navHome: "Pradžia",
  navDashboard: "Skydelis",
  navFundraisers: "Rinkliavos",
  navDonations: "Aukos",
  navAccount: "Paskyra",
  navProfile: "Profilis",

  searchPlaceholder: "Ieškokite rinkliavų, tikslų ar organizatorių",
  searchEmpty: "Pradėkite rašyti, kad rastumėte rinkliavas",
  searchResults: "Rezultatai",
  searchNoResults: "Nerasta rinkliavų pagal jūsų paiešką",

  // Hero
  heroTitle1: "Pasaulinė",
  heroTitle2: "lėšų rinkimo",
  heroTitle3: "platforma",
  heroSubtitle: "Kiekviena istorija svarbi. Kiekviena auka skaičiuojama. Per kelias minutes pradėkite savo rinkliavą ir pasiekite pasaulinę dosnumo bendruomenę.",
  heroFeeFree: "Jokio mokesčio pradžiai",
  heroReviewed: "Kiekviena rinkliava peržiūrima prieš paskelbiant",
  heroWithdraw: "Atsiimkite lėšas į banko sąskaitą bet kada",
  heroFeaturedStoryBadge: "Rekomenduojama istorija",
  heroUnmuteVideo: "Įjungti garsą",
  heroMuteVideo: "Išjungti garsą",
  heroWatchOnYoutube: "Žiūrėti per YouTube",
  heroHelpFamilyLithuania: "Padėk šeimai Lietuvoje",
  heroDonateNow: "Paaukoti dabar",

  // ─── Checkout success ──────────────────────────────────────────────────
  successHeading: "Ačiū už jūsų auką!",
  successTagline: "Kiekviena auka – nauja viltis.",
  successBody: "Jūsų gerumas šiandien atneša tikrus pokyčius kažkieno gyvenime. Kvitą išsiuntėme į jūsų el. paštą, tad stebėkite gautuosius ir sužinosite apie jūsų aukos poveikį.",
  successBackHome: "Grįžti į pradžią",
  successViewCampaign: "Peržiūrėti kampaniją",
  successShare: "Pasidalinti",
  successShareText: "Ką tik parėmiau projektą Benefactor platformoje. Kiekviena auka yra nauja viltis. Prisijunk:",
  successReceiptNote: "Kvitas išsiųstas į jūsų el. paštą. Mokėjimus saugiai apdoroja Stripe.",

  // Featured
  featuredHeading: "Rekomenduojama rinkliava",
  featuredViewAll: "Žiūrėti visas",
  featuredRaisedOf: "surinkta iš {total}",
  featuredPctFunded: "Surinkta {pct} %",
  featuredStatRaised: "Surinkta",
  featuredStatDonors: "Aukotojai",
  featuredStatGoal: "Tikslas",
  featuredShareAria: "Dalintis rinkliava",

  // Categories
  categoriesHeading: "Kategorijos",
  catMedical: "Medicina",
  catEmergency: "Skubi pagalba",
  catEducation: "Švietimas",
  catAnimals: "Gyvūnai",
  catBusiness: "Verslas",
  catCommunity: "Bendruomenė",
  catEnvironment: "Aplinka",
  catCreative: "Kūryba",
  catSport: "Sportas",
  catFamily: "Šeima",
  catMemorial: "Atminimas",
  catTravel: "Kelionės",

  // How & Trust
  howHeading: "Kaip tai veikia",
  howStep1Title: "Sukurkite rinkliavą",
  howStep1Desc: "Papasakokite istoriją, pridėkite nuotrauką ir nurodykite tikslą. Užtruks vos kelias minutes.",
  howStep2Title: "Pasidalykite su artimaisiais",
  howStep2Desc: "Išsiųskite rinkliavos nuorodą draugams, šeimai ir pasaulinei auditorijai.",
  howStep3Title: "Gaukite aukas",
  howStep3Desc: "Lėšos pervedamos į jūsų patikrintą banko sąskaitą. Jokio platformos mokesčio.",
  trustHeading: "Kaip apsaugota jūsų auka",
  trustItem1Title: "Mokėjimus saugo Stripe",
  trustItem1Desc: "Visus mokėjimus tvarko Stripe, atitinkantis PCI DSS 1 lygio reikalavimus.",
  trustItem2Title: "Patikrinti organizatoriai",
  trustItem2Desc: "Kiekviena rinkliava peržiūrima, o organizatoriaus tapatybė patvirtinama prieš paskelbiant.",
  trustItem3Title: "Tiesioginis pervedimas į banką",
  trustItem3Desc: "Lėšos pervedamos į jūsų patikrintą banko sąskaitą SEPA arba banko pavedimu.",
  poweredBy: "Sprendimas:",

  // Showcase
  showcaseBadge: "Būsimas projektas",
  showcaseTitle: "Vaikų stovyklos centras",
  showcaseDesc: "Mūsų kita iniciatyva yra Vaikų stovyklos centras Lietuvoje, saugi erdvė, kurioje vaikai gali mokytis, žaisti ir augti kartu. Labai greitai pradėsime rinkliavos kampaniją. Sekite mus, palaikykite projektą ir kartu su mumis stebėkite kiekvieną kelionės etapą.",
  showcaseCta: "Paremti projektą",
  // ─── Kids Camp support modal ───
  supportClose: "Uždaryti",
  supportComingSoonBadge: "Greitai",
  supportHeading: "Prisijunkite prie Vaikų stovyklos centro kelionės",
  supportLeadCopy:
    "Labai greitai pradėsime rinkliavos kampaniją. Iki tol galite pasidalinti idėjomis, tapti partneriais, paaukoti arba prisijungti kaip savanoriai. Kiekvienas laiškas pasiekia mūsų komandą tiesiogiai.",
  supportRoleLabel: "Norėčiau prisidėti kaip",
  supportRole_donor: "Aukotojas",
  supportRole_volunteer: "Savanoris",
  supportRole_partner: "Partneris arba rėmėjas",
  supportRole_other: "Kitaip",
  supportName: "Jūsų vardas",
  supportEmail: "El. paštas",
  supportMessage: "Jūsų žinutė",
  supportMessagePlaceholder:
    "Pasidalinkite pasiūlymu, organizacine idėja arba kaip norėtumėte prisidėti…",
  supportPrivacyNote:
    "Jūsų duomenys siunčiami tiesiai Benefactor komandai. Niekada jų nedalinsime.",
  supportSubmit: "Siųsti komandai",
  supportThanksTitle: "Ačiū, kad žengiate kartu",
  supportThanksBody:
    "Jūsų žinutė paruošta el. pašto programoje. Atsakysime kuo greičiau ir informuosime apie projekto eigą.",
  showcaseImageCaption: "Netrukus — vieta, sukurta kiekvienam vaikui",
  showcaseImageAlt: "Vaikų stovyklos centras",

  // Useful
  usefulBadge: "Naudingos nuorodos",
  usefulHeading: "Norite sužinoti daugiau apie lėšų rinkimą?",
  usefulLink1Title: "Kas yra lėšų rinkimas?",
  usefulLink1Desc: "Viskas, ką reikia žinoti apie lėšų rinkimą.",
  usefulLink2Title: "Kaip rinkti lėšas",
  usefulLink2Desc: "Kaip pradėti kurti savo rinkliavos puslapį.",
  usefulLink3Title: "Lėšų rinkimo patarimai",
  usefulLink3Desc: "Kaip surinkti kuo daugiau aukų.",
  usefulLink4Title: "Sukurkite tobulą rinkliavos puslapį",
  usefulLink4Desc: "Penki paprasti žingsniai sėkmingam rinkliavos puslapiui.",

  // Footer
  footerCategories: "Kategorijos",
  footerAbout: "Apie",
  footerStartLabel: "Pradėti rinkliavą",
  footerFundraisingCategories: "Rinkliavų kategorijos",
  footerHowItWorks: "Kaip veikia Benefactor",
  footerAboutLink: "Apie Benefactor",
  footerCareers: "Karjera",
  footerCopyright: "© {year} Benefactor platforma. Visos teisės saugomos.",
  footerTrustSecure: "Saugūs mokėjimai",
  footerTrustVerified: "Patikrintas lėšų rinkimo procesas",
  footerTrustData: "Duomenų apsauga",
  footerLegalTerms: "Sąlygos",
  footerLegalPrivacy: "Privatumas",
  footerLegalContact: "Kontaktai",
  footerStripeNotice: "Visas aukas tvarko Stripe per šifruotus kanalus. Mes niekada nesaugome pilnų kortelės duomenų. Kiekviena rinkliava peržiūrima prieš paskelbiant, o organizatoriaus tapatybė patikrinama.",

  localeRegionLanguage: "Regionas ir kalba",
  localeSave: "Išsaugoti nustatymus",
  localeClose: "Uždaryti",
  localeLanguage: "Kalba",
  localeCountry: "Šalis",
  localeUpdateSettings: "Atnaujinkite savo nustatymus",
  localeUpdateDesc: "Nurodykite, kokia kalba kalbate ir kur gyvenate.",
  localeSelectLanguage: "Pasirinkite kalbą",
  localeSelectCountry: "Pasirinkite šalį",
  cancel: "Atšaukti",
  save: "Išsaugoti",

  // Campaign / common
  raised: "Surinkta",
  donations: "Aukos",
  goal: "Tikslas",
  donatePlain: "Aukoti",
  share: "Dalintis",
  organizer: "Organizatorius",
  contact: "Susisiekti",
  raisedOfGoal: "surinkta iš {total} tikslo",
  donorsLabel: "aukotojai",
  recentDonors: "Naujausi aukotojai",
  totalCount: "iš viso {count}",
  sortRecent: "Naujausi",
  sortTop: "Didžiausios",
  anonymous: "Anonimas",
  showLess: "Rodyti mažiau",
  seeAllDonors: "Žiūrėti visus {count} aukotojų",
  funded: "surinkta",
  verified: "Patvirtinta",
  readMore: "Skaityti daugiau",
  readLess: "Skaityti mažiau",
  aboutThisCampaign: "Apie šią rinkliavą",
  relatedFundraisers: "Panašios rinkliavos",
  prevImage: "Ankstesnė nuotrauka",
  nextImage: "Kita nuotrauka",
  openFullscreen: "Atidaryti per visą ekraną",
  viewImage: "Žiūrėti",
  galleryImage: "Galerijos nuotrauka {n}",
  showImage: "Rodyti nuotrauką {n}",

  // Share modal
  shareTitle: "Pasidalinkite šia rinkliava",
  shareSubtitle: "Padėkite skleisti žinią — kiekvienas pasidalijimas leidžia pasiekti daugiau žmonių.",
  shareCopy: "Kopijuoti nuorodą",
  shareCopied: "Nuoroda nukopijuota",
  shareWhatsapp: "WhatsApp",
  shareTwitter: "X / Twitter",
  shareFacebook: "Facebook",
  shareTelegram: "Telegram",
  shareEmail: "El. paštas",
  shareNative: "Daugiau parinkčių",
  shareClose: "Uždaryti",

  // Checkout
  checkoutYouAreDonatingTo: "Jūs aukojate:",
  checkoutCampaignTitle: "Padėkite šeimai Lietuvoje šiltai išgyventi žiemą",
  checkoutPctFunded: "Surinkta {pct} %",
  checkoutToGo: "Liko {amount}",
  checkoutGiveOnce: "Vienkartinė auka",
  checkoutMonthly: "Kas mėnesį",
  checkoutMonthlyNote: "Reguliarios aukos kuria tvarią paramą tikslui.",
  checkoutChooseAmount: "Pasirinkite sumą",
  checkoutPopular: "Populiaru",
  checkoutOtherAmount: "Kita suma",
  checkoutTipHeading: "Palaikykite Benefactor",
  checkoutTipDesc: "Iš organizatorių neimame jokio mokesčio. Arbatpinigiai yra savanoriški ir padeda mums išlaikyti platformą nemokamą.",
  checkoutTipPercentLabel: "Arbatpinigių procentas",
  checkoutApply: "Pritaikyti",
  checkoutCancel: "Atšaukti",
  checkoutUseSlider: "Naudoti slankiklį",
  checkoutEnterCustomTip: "Įvesti savo arbatpinigius",
  checkoutPaymentMethod: "Mokėjimo būdas",
  checkoutOrPayCard: "Arba mokėti kortele",
  checkoutCurrency: "Aukos valiuta",
  checkoutCurrencyNote: "Priimame bet kuria valiuta. Stripe atlieka konvertavimą į mūsų sąskaitą.",
  checkoutEmail: "El. paštas kvitui",
  checkoutEmailPlaceholder: "tu@elpastas.lt",
  checkoutEmailNote: "Atsiųsime kvitą ir patvirtinimą mokesčių tikslais. Jūsų el. pašto niekam neatskleidžiame.",
  checkoutEmailRequired: "Reikalingas el. paštas",
  checkoutEmailRequiredDesc: "Įveskite galiojantį el. paštą, kad galėtume atsiųsti aukos kvitą.",
  checkoutPaypalSoonTitle: "PayPal greitai bus aktyvus",
  checkoutPaypalSoonDesc: "PayPal kol kas neaktyvus. Pasirinkite Apple Pay, Google Pay, Revolut Pay arba Kortelę.",
  checkoutComingSoon: "Netrukus",
  checkoutOneTap: "Vienu palietimu",
  checkoutPaypal: "PayPal",
  checkoutApplePay: "Apple Pay",
  checkoutGooglePay: "Google Pay",
  checkoutRevolutPay: "Revolut Pay",
  checkoutCard: "Kredito arba debeto kortelė",
  checkoutAnonOption: "Nerodyti mano vardo viešai rinkliavos puslapyje.",
  checkoutShowName: "Rodyti mano vardą viešai rinkliavos puslapyje.",
  checkoutUpdatesOption: "Norėčiau retkarčiais gauti naujienas iš Benefactor.",
  checkoutSummary: "Santrauka",
  checkoutYourDonation: "Jūsų auka",
  checkoutBenefactorTip: "Arbatpinigiai Benefactor",
  checkoutTotalToday: "Iš viso šiandien",
  checkoutDonateNow: "Aukoti dabar",
  checkoutAgreeTerms: "Tęsdami sutinkate su mūsų",
  checkoutAnd: "ir",
  checkoutTermsLink: "sąlygomis",
  checkoutPrivacyLink: "privatumo politika",
  checkoutProtectionTitle: "Jūsų auka yra apsaugota",
  checkoutProtectionDesc: "Mokėjimus tvarko Stripe per šifruotus kanalus. Retais sukčiavimo atvejais garantuojame pilną grąžinimą iki vienerių metų.",
  checkoutLearnMore: "Sužinoti daugiau",
  checkoutPaymentFailed: "Mokėjimas nepavyko",
  checkoutPageFooterTagline: "Pasaulinė lėšų rinkimo platforma",

  // How page
  howPageEyebrow: "Kaip tai veikia",
  howPageTitlePart1: "Nuo istorijos iki",
  howPageTitleEmph: "paramos",
  howPageTitlePart2: " — per kelias minutes.",
  howPageLede: "Trys žingsniai. Jokio platformos mokesčio. Kiekviena rinkliava peržiūrima prieš paskelbiant.",
  howStepAltTitle1: "Pradėkite rinkliavą",
  howStepAltDesc1: "Nustatykite tikslą, parašykite istoriją ir pridėkite nuotraukų. Užtruks vos kelias minutes.",
  howStepAltTitle2: "Pasidalykite su tinklu",
  howStepAltDesc2: "Išsiųskite rinkliavos nuorodą draugams, šeimai ir socialiniuose tinkluose.",
  howStepAltTitle3: "Gaukite aukas",
  howStepAltDesc3: "Stebėkite pažangą, padėkokite aukotojams ir bet kada atsiimkite lėšas į banką.",
  howWhyHeading: "Kodėl renkasi Benefactor",
  howFeat1Title: "0 % platformos mokestis",
  howFeat1Desc: "Benefactor niekada nepasilieka savo dalies. Daugiau pinigų atitenka tiems, kuriems jų reikia.",
  howFeat2Title: "Aukotojų apsauga",
  howFeat2Desc: "Kiekviena rinkliava peržiūrima, o organizatoriaus tapatybė patikrinama prieš paskelbiant.",
  howFeat3Title: "Greitas lėšų atsiėmimas",
  howFeat3Desc: "Pervedame lėšas į jūsų patikrintą banko sąskaitą SEPA arba banko pavedimu, kai tik reikia.",
  howFeat4Title: "Veikia visoje Europoje",
  howFeat4Desc: "Rinkite ir aukokite iš bet kurios Europos vietos. Atitinkame reikalavimus nuo pirmos dienos.",
  howReadyHeading: "Pasiruošę pradėti?",
  howReadyDesc: "Užtruksite vos kelias minutes paleisti rinkliavą ir ja pasidalinti.",

  // About page
  aboutEyebrow: "Apie",
  aboutTitlePart1: "Dosnumas, padarytas",
  aboutTitleEmph: "paprastu",
  aboutTitlePart2: ".",
  aboutLede: "Benefactor — lėšų rinkimo platforma, sukurta skaidrumo, pasitikėjimo ir nulinio mokesčio pagrindu.",
  aboutOurStory: "Mūsų istorija",
  aboutStoryP1: "Benefactor atsirado iš klausimo, kurio negalėjome ignoruoti: kodėl geriems žmonėms vis dar taip sunku rinkti pinigus geriems tikslams? Trintį matėme savo akimis. Nepasitikėjimą. Mokesčius. Platformas, kurios pasiimdavo per daug ir grąžindavo per mažai.",
  aboutStoryP2: "Tad sukūrėme kažką kitokio. Ar tai šeima, susidūrusi su netikėtomis išlaidomis, bendruomenė, atsigaunanti po krizės, ar studentas, siekiantis galimybės — Benefactor egzistuoja tam, kad sumažintų atstumą tarp užuojautos ir veiksmo.",
  aboutWhatWeDo: "Ką mes darome",
  aboutWhatWeDoP: "Suteikiame paprasčiausią ir skaidriausią būdą rinkti ir aukoti pinigus internete. Jokio platformos mokesčio. Patikrintos rinkliavos. Bankinio lygio saugumas. Ir komanda, kuri peržiūri kiekvieną rinkliavą prieš paskelbiant.",
  aboutCommitment: "Mūsų įsipareigojimas",
  aboutStat1Label: "Platformos mokestis",
  aboutStat2Label: "Peržiūros laikas",
  aboutStat3Label: "Šifruoti mokėjimai",
  aboutStat4Label: "Atitinka standartus",
  aboutValues: "Mūsų vertybės",
  aboutValue1Title: "Radikalus skaidrumas",
  aboutValue1Desc: "Kiekviena rinkliava peržiūrėta. Kiekvienas mokėjimas atsekamas. Pasitikėjimas užtarnaujamas, o ne deklaruojamas.",
  aboutValue2Title: "Pirmiausia — paprastumas",
  aboutValue2Desc: "Apsėstai šaliname trukdžius. Jei atrodo sudėtinga — vadinasi, dar nebaigta.",
  aboutValue3Title: "Užuojauta be sienų",
  aboutValue3Desc: "Geras tikslas neturi tautybės. Kuriame taip, kad dosnumas tekėtų ten, kur jo reikia.",

  // Careers
  careersEyebrow: "Karjera",
  careersTitlePart1: "Kurkite įrankius, padedančius žmonėms",
  careersTitleEmph: "padėti vieniems kitiems",
  careersTitlePart2: ".",
  careersLede: "Ieškome aistringų žmonių, norinčių prisijungti prie mūsų misijos.",
  careersWhyHeading: "Kodėl dirbti Benefactor",
  careersPerk1Title: "Prasmingas poveikis",
  careersPerk1Desc: "Jūsų darbas tiesiogiai padeda žmonėms rinkti lėšas svarbiausiems jiems tikslams.",
  careersPerk2Title: "Pirmiausia nuotoliu",
  careersPerk2Desc: "Dirbkite iš bet kur lanksčiu grafiku ir asinchroniniu bendradarbiavimu.",
  careersPerk3Title: "Augimas ir mokymasis",
  careersPerk3Desc: "Gaukite mentorystę, mokymosi biudžetą ir galimybes plėtoti karjerą.",
  careersPerk4Title: "Konkurencingos lengvatos",
  careersPerk4Desc: "Visapusiškas sveikatos draudimas, dosnios atostogos ir akcijų paketai visai komandai.",
  careersPerk5Title: "Įtrauki komanda",
  careersPerk5Desc: "Vertiname įvairovę ir kuriame aplinką, kurioje gali klestėti kiekvienas.",
  careersPerk6Title: "Atiduoti bendruomenei",
  careersPerk6Desc: "Mokamos savanorystės dienos ir asmeninių aukų prilyginimas jums rūpimoms iniciatyvoms.",
  careersOpenPositions: "Atviros pozicijos",
  careersVolunteerCallout:
    "Taip pat ieškome savanorių. Jei norite skirti savo laiko, įgūdžių ar idėjų, kad mūsų kampanijos pasiektų daugiau žmonių, kviečiame prisijungti.",
  careersApply: "Pretenduoti",
  careersDeptEngineering: "Inžinerija",
  careersDeptDesign: "Dizainas",
  careersDeptCommunity: "Bendruomenė",
  careersDeptAnalytics: "Analitika",
  careersDeptMarketing: "Rinkodara",
  careersFullTime: "Visa darbo diena",
  careersVolunteer: "Savanoris",
  careersRoleVolunteer: "Savanoris — padėk mums kurti platformą",
  careersLocRemote: "Nuotolinis",
  careersLocLondon: "Londonas, JK",
  careersRoleSeniorFrontend: "Vyresnysis frontend inžinierius",
  careersRoleProductDesigner: "Produkto dizaineris",
  careersRoleCommunityManager: "Bendruomenės vadovas",
  careersRoleDataAnalyst: "Duomenų analitikas",
  careersRoleMarketingSpecialist: "Rinkodaros specialistas",
  careersRoleContentEditor: "Turinio redaktorius",
  careersNoRoleHeading: "Nematote tinkamos pozicijos?",
  careersNoRoleDesc: "Visada ieškome talentingų ir aistringų žmonių. Atsiųskite CV ir papasakokite, kuo norėtumėte prisidėti.",
  careersGetInTouch: "Susisiekti",

  // Wizard
  wizardStepOf: "{current} žingsnis iš {total}",
  wizardBack: "Atgal",
  wizardSkip: "Praleisti",
  wizardContinue: "Tęsti",
  wizardReview: "Peržiūrėti",
  wizardSubmit: "Pateikti",
  wizardStepTitle0: "Pradėkime jūsų rinkliavos kelionę.",
  wizardStepSubtitle0: "Pasirinkite kategoriją ir vietą. Likusiu pasirūpinsime mes.",
  wizardStepTitle1: "Kam bus skirtos lėšos?",
  wizardStepSubtitle1: "Pasakykite mums, kam skirtos surinktos lėšos.",
  wizardStepTitle2: "Nustatykite rinkliavos tikslą.",
  wizardStepSubtitle2: "Vėliau visada galėsite jį pakeisti.",
  wizardStepTitle3: "Išryškinkite savo rinkliavą.",
  wizardStepSubtitle3: "Gera nuotrauka ar trumpas vaizdo įrašas pakeičia viską.",
  wizardStepTitle4: "Papasakokite aukotojams savo istoriją.",
  wizardStepSubtitle4: "Aiški istorija padeda užmegzti ryšį su aukotojais.",
  wizardStepTitle5: "Pateikite peržiūrai.",
  wizardStepSubtitle5: "Pridėkite kontaktinius duomenis ir pateikite patvirtinimui.",
  wizardStepTitle6: "Jūsų rinkliava peržiūrima.",
  wizardStepSubtitle6: "Mūsų komanda peržiūrės ir susisieks su jumis per 24 valandas.",
  wizardSidebarStep1: "Kategorija",
  wizardSidebarStep2: "Gavėjas",
  wizardSidebarStep3: "Tikslas",
  wizardSidebarStep4: "Vaizdai",
  wizardSidebarStep5: "Istorija",
  wizardSidebarStep6: "Peržiūra",

  stepCategoryHeading: "Kur keliaus lėšos?",
  stepCategoryDesc: "Pasirinkite vietą, kurioje planuojate atsiimti lėšas.",
  stepCategorySupportedCountries: "Palaikomos šalys",
  stepCategoryCountry: "Šalis",
  stepCategoryPostcode: "Pašto kodas",
  stepCategoryPostcodePlaceholder: "pvz., LT-01108",
  stepCategoryWhichDescribes: "Kas geriausiai apibūdina jūsų rinkliavą?",

  stepBeneficiaryHeading: "Kam renkate lėšas?",
  stepBenYourselfTitle: "Sau",
  stepBenYourselfDesc: "Lėšos pervedamos į jūsų banko sąskaitą savo reikmėms.",
  stepBenSomeoneTitle: "Kitam asmeniui",
  stepBenSomeoneDesc: "Pakvieskite gavėją gauti lėšas arba paskirstykite jas patys.",
  stepBenCharityTitle: "Labdaros organizacijai",
  stepBenCharityDesc: "Lėšos pervedamos jūsų pasirinktai ne pelno organizacijai.",

  stepGoalAmount: "Tikslo suma",
  stepGoalHint: "Tokios rinkliavos kaip jūsų paprastai siekia 3 500 € ar daugiau.",
  stepGoalRecommended: "Rekomenduojama",
  stepGoalAutoTitle: "Automatinis tikslo nustatymas",
  stepGoalAutoDesc: "Mes laipsniškai koreguojame jūsų tikslą, kai gaunamos aukos.",
  stepGoalMore: "Daugiau",
  stepGoalAutoAria: "Įjungti automatinį tikslą",

  stepMediaHeading: "Pridėkite viršelio nuotrauką ar vaizdo įrašą",
  stepMediaDesc: "Aiški, tikra nuotrauka padeda aukotojams užmegzti ryšį su jūsų istorija. Vėliau galėsite ją pakeisti.",
  stepMediaReplace: "Pakeisti",
  stepMediaRemove: "Pašalinti",
  stepMediaRemoveAria: "Pašalinti viršelį",
  stepMediaDropHint: "Vilkite nuotrauką čia arba spustelėkite, kad įkeltumėte",
  stepMediaFileHint: "JPG, PNG arba MP4 iki 50 MB",
  stepMediaCoverAlt: "Viršelio peržiūra",

  stepStoryTitleLabel: "Rinkliavos pavadinimas",
  stepStoryTitlePlaceholder: "Padėkite šeimai...",
  stepStoryStoryLabel: "Jūsų istorija",
  stepStoryStoryPlaceholder: "Papasakokite, kodėl renkate lėšas, kam jos padės ir kaip bus panaudotos.",
  stepStoryTip: "Patarimas: aiški ir nuoširdi istorija surenka dvigubai daugiau nei neaiški.",

  stepReviewNotSet: "Nenurodyta",
  stepReviewEdit: "Redaguoti",
  stepReviewTitle: "Pavadinimas",
  stepReviewGoal: "Tikslas",
  stepReviewCategory: "Kategorija",
  stepReviewLocation: "Vieta",
  stepReviewStory: "Istorija",
  stepReviewContact: "Kontaktiniai duomenys",
  stepReviewEmail: "El. paštas",
  stepReviewPhone: "Telefonas",
  stepReviewEmailPlaceholder: "vardas@pavyzdys.lt",
  stepReviewPhonePlaceholder: "+370 600 00000",
  stepReviewHint: "Šiuos duomenis naudoja mūsų komanda, norėdama susisiekti su jumis dėl trumpo peržiūros pokalbio prieš paskelbiant rinkliavą.",
  stepReviewPreview: "Peržiūra",
  stepReviewPreviewSoon: "Peržiūra netrukus bus",
  stepReviewSubmit: "Pateikti peržiūrai",
  stepReviewCoverAlt: "Viršelis",

  stepShareSubmissionReceived: "Paraiška gauta.",
  stepShareDesc: "Jūsų rinkliava išsiųsta mūsų komandai peržiūrai. Kiekvieną rinkliavą tikriname rankiniu būdu, kad platforma išliktų patikima.",
  stepShareWhatNext: "Kas vyks toliau",
  stepShareStep1Title: "Komandos peržiūra",
  stepShareStep1Desc: "Mūsų komanda peržiūri jūsų rinkliavą per 24–48 valandas.",
  stepShareStep2Title: "Susitikimo prašymas",
  stepShareStep2Desc: "Susisiekiame el. paštu arba telefonu, kad suplanuotume trumpą pažintinį pokalbį.",
  stepShareStep3Title: "Paskelbimas",
  stepShareStep3Desc: "Patvirtinus, jūsų rinkliava paskelbiama platformoje.",
  stepShareGoDashboard: "Į skydelį",
  stepShareBackHome: "Grįžti į pradžią",

  // Auth
  authWelcomeBack: "Sveiki sugrįžę",
  authCreateAccount: "Sukurkite paskyrą",
  authSigninDesc: "Prisijunkite, kad tęstumėte.",
  authSignupDesc: "Pradėkite savo rinkliavą per kelias minutes.",
  authContinueGoogle: "Tęsti su Google",
  authOr: "arba",
  authEmail: "El. paštas",
  authEmailPlaceholder: "vardas@pavyzdys.lt",
  authFullName: "Vardas ir pavardė",
  authNamePlaceholder: "Jonas Jonaitis",
  authPassword: "Slaptažodis",
  authPasswordPlaceholder: "Bent 8 simboliai",
  authShowPassword: "Rodyti slaptažodį",
  authHidePassword: "Slėpti slaptažodį",
  authContinue: "Tęsti",
  authSignIn: "Prisijungti",
  authCreate: "Sukurti paskyrą",
  authUseDifferentEmail: "Naudoti kitą el. paštą",
  authNewToBenefactor: "Naujas Benefactor naudotojas?",
  authAlreadyHave: "Jau turite paskyrą?",
  authCreateLink: "Sukurti paskyrą",
  authSignInLink: "Prisijungti",
  authAgreeTerms: "Tęsdami sutinkate su mūsų",
  authAnd: "ir",
  authTerms: "sąlygomis",
  authPrivacy: "privatumo politika",
  authBackToBenefactor: "Grįžti į Benefactor",
  authFailed: "Autentifikacija nepavyko",

  // Dashboard
  dashYourAccount: "Jūsų paskyra",
  dashTitle: "Skydelis",
  dashNewFundraiser: "Nauja rinkliava",
  dashYourFundraisers: "Jūsų rinkliavos",
  dashRecentActivity: "Naujausia veikla",
  dashQuickActions: "Greiti veiksmai",
  dashStatTotalRaised: "Iš viso surinkta",
  dashStatDonations: "Aukos",
  dashStatSupporters: "Rėmėjai",
  dashStatShares: "Pasidalijimai",
  dashStatChangeWeek: "+{value} % šią savaitę",
  dashStatChangeToday: "+{value} šiandien",
  dashStatChangeNew: "+{value} nauji",
  dashStatChangeWeekCount: "+{value} šią savaitę",
  dashSampleFundraiserTitle: "Padėkite finansuoti mano mokslo kelionę",
  dashSampleFundraiserMeta: "Sukurta prieš 2 dienas · Švietimas",
  dashRaisedLower: "surinkta",
  dashOfGoalLower: "iš {amount} tikslo",
  dashDonationsLower: "aukos",
  dashManage: "Valdyti",
  dashLoading: "Įkeliama…",
  dashActDonated: "paaukojo",
  dashActShared: "pasidalijo jūsų rinkliava",
  dashActTime2m: "prieš 2 minutes",
  dashActTime15m: "prieš 15 minučių",
  dashActTime1h: "prieš 1 valandą",
  dashActTime2h: "prieš 2 valandas",
  dashActTime3h: "prieš 3 valandas",
  dashActDonorEmma: "Emma W.",
  dashActDonorJames: "James M.",
  dashActDonorSarah: "Sarah K.",
  dashActDonorAli: "Ali R.",
  dashActDonorAnonymous: "Anonimas",
  qaShareTitle: "Pasidalinti rinkliava",
  qaShareDesc: "Pasidalykite socialiniuose tinkluose, el. paštu arba nukopijuokite nuorodą.",
  qaEditTitle: "Redaguoti rinkliavą",
  qaEditDesc: "Atnaujinkite istoriją, nuotraukas ar tikslą.",
  qaWithdrawTitle: "Atsiimti lėšas",
  qaWithdrawDesc: "Perveskite surinktas lėšas į savo banko sąskaitą.",

  // Profile
  profileBreadcrumbDashboard: "Skydelis",
  profileBreadcrumbProfile: "Profilis",
  profileSettings: "Nustatymai",
  profileTitle: "Profilis",
  profilePersonalInfo: "Asmeninė informacija",
  profileNotifications: "Pranešimai",
  profileFullName: "Vardas ir pavardė",
  profileEmail: "El. paštas",
  profilePhone: "Telefonas",
  profileLanguage: "Pageidaujama kalba",
  profileBio: "Apie mane",
  profileBioPlaceholder: "Trumpai papasakokite apie save.",
  profileEmailUpdates: "Naujienos el. paštu",
  profileEmailUpdatesDesc: "Gaukite rinkliavos naujienas ir aukų kvitus el. paštu.",
  profileSmsUpdates: "SMS pranešimai",
  profileSmsUpdatesDesc: "Gaukite svarbiausius pranešimus žinutėmis.",
  profileKeepCurrent: "Atnaujinkite duomenis, kad mūsų komanda galėtų susisiekti dėl rinkliavų peržiūros.",
  profileSaved: "Išsaugota",
  profileSave: "Išsaugoti pakeitimus",
  profileChangePhoto: "Pakeisti nuotrauką",
  profileMemberSince: "Narys nuo 2024 m. balandžio · Londonas, JK",
  profileTagVerified: "Patvirtintas",
  profileTagFundraiser: "Organizatorius",
  profileStatDonations: "Aukos",
  profileStatProjects: "Projektai",

  // Errors / not found / loading
  errorSomethingWentWrong: "Kažkas nepavyko",
  errorDefault: "Įvyko netikėta klaida. Bandykite dar kartą.",
  errorTryAgain: "Bandyti dar kartą",
  notFoundTitle: "Puslapis nerastas",
  notFoundDesc: "Puslapio, kurio ieškote, nėra arba jis buvo perkeltas.",
  notFoundBackHome: "Grįžti į pradžią",
  notFoundLearnHow: "Sužinokite, kaip tai veikia",
  loading: "Įkeliama…",
};

// Other languages fall back to English (existing project behavior).
const ru: Dict = {};
const tr: Dict = {};
const de: Dict = {};
const fr: Dict = {};
const es: Dict = {};

const dict: Record<LangCode, Dict> = { en, lt, ru, tr, de, fr, es };

// Helper: substitute {var} tokens.
function interpolate(template: string, params?: Record<string, string | number>): string {
  if (!params) return template;
  return template.replace(/\{(\w+)\}/g, (_, k) =>
    params[k] !== undefined ? String(params[k]) : `{${k}}`
  );
}

interface LanguageContextType {
  language: LangCode;
  setLanguage: (lang: LangCode) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  language: "en",
  setLanguage: () => {},
  t: (key) => key,
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<LangCode>("en");

  useEffect(() => {
    const saved = localStorage.getItem("benefactor_lang");
    if (saved && SUPPORTED.includes(saved as LangCode)) {
      setLanguageState(saved as LangCode);
    } else {
      const legacy = localStorage.getItem("benefactor_locale_lang");
      if (legacy && SUPPORTED.includes(legacy as LangCode)) {
        setLanguageState(legacy as LangCode);
      }
    }
  }, []);

  const setLanguage = (lang: LangCode) => {
    setLanguageState(lang);
    localStorage.setItem("benefactor_lang", lang);
    localStorage.setItem("benefactor_locale_lang", lang);
    document.documentElement.lang = lang;
  };

  const t = (key: string, params?: Record<string, string | number>) => {
    const raw = dict[language]?.[key] || dict.en[key] || key;
    return interpolate(raw, params);
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
